Fix FromJSON1 instance of Sum
haskell/aeson pull request #861
Opened 2021-08-08 08:29 UTC by Patil2099

Fixes  #860

2021-08-08 11:29 UTC, phadej requested changes
Please add test(s) to SerializationFormatSpec.hs

2021-08-08 16:27 UTC, Vlix commented
The `... <?> Key x` part of the `Parser` doesn't influence serialization, right?
So the test should be a failed parsing, and make sure the error message is correct?

2021-08-17 17:17 UTC, bergmark commented
> The `... <?> Key x` part of the `Parser` doesn't influence serialization, right?
> So the test should be a failed parsing, and make sure the error message is correct?

Right. I think the right place for the test is the golden tests in tests/ErrorMessages.hs (`simple` / `output`)

2021-09-22 06:44 UTC, taasan commented on src/Data/Aeson/Types/FromJSON.hs
> +        | key == inr = InR <$> liftParseJSON p pl value <?> Key inr
Wouldn't something like this be less error prone? (Change `f` and `g` to more meaningful names)

```haskell
    liftParseJSON p pl (Object (H.toList -> [(key, value)]))
        | key == inl = f InL
        | key == inr = f InR
      where
        f g = g <$> liftParseJSON p pl value <?> Key key
```

2021-09-22 08:12 UTC, phadej commented
I'm sorry. I completely misunderstood the PR. if it's fixing the `Key` only we don't necessarily need a test.

2021-09-22 08:12 UTC, merged